"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/utils/supabase/client";
import { Plus, Trash2, RefreshCw } from "lucide-react";

type Product={id:string;name:string;price:number;original_price:number|null;image:string|null;tag:string|null;rating:number;reviews:string;has_3d:boolean};
const empty={name:"",price:"",original_price:"",image:"",tag:"",rating:"5",reviews:"0",has_3d:false};
export default function ProductsAdmin(){const[supabase]=useState(()=>createClient());const[products,setProducts]=useState<Product[]>([]);const[form,setForm]=useState(empty);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
async function load(){setLoading(true);const{data,error}=await supabase.from("products").select("*").order("created_at",{ascending:false});if(error)setError(error.message);else setProducts((data??[]) as Product[]);setLoading(false)}useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();setError("");const price=Number(form.price);if(!form.name.trim()||!Number.isFinite(price)||price<0){setError("نام و قیمت معتبر وارد کنید.");return}const{error}=await supabase.from("products").insert({name:form.name.trim(),price,original_price:form.original_price?Number(form.original_price):null,image:form.image.trim()||null,tag:form.tag.trim()||null,rating:Number(form.rating)||5,reviews:form.reviews.trim()||"0",has_3d:form.has_3d});if(error)setError(error.message);else{setForm(empty);await load()}}
async function remove(id:string){if(!confirm("این محصول حذف شود؟"))return;const{error}=await supabase.from("products").delete().eq("id",id);if(error)setError(error.message);else setProducts(p=>p.filter(x=>x.id!==id))}
return <><div className="flex justify-between items-end mb-7"><div><p className="text-[#B88A3A] font-bold">فروشگاه</p><h2 className="text-4xl font-black">محصولات</h2></div><button onClick={load} className="rounded-full border border-[#062A43]/10 px-4 py-2 flex gap-2"><RefreshCw size={17}/> بروزرسانی</button></div><div className="grid lg:grid-cols-[360px_1fr] gap-6"><form onSubmit={add} className="bg-[#FCFAF6] border border-[#B88A3A]/20 rounded-3xl p-6 h-fit space-y-3"><h3 className="text-xl font-black flex gap-2"><Plus/> افزودن محصول</h3>{["name","price","original_price","image","tag","rating","reviews"].map(k=><input key={k} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={{name:"نام محصول",price:"قیمت",original_price:"قیمت قبلی (اختیاری)",image:"مسیر تصویر /product_img/...",tag:"برچسب",rating:"امتیاز",reviews:"تعداد نظر"}[k]} className="w-full rounded-xl bg-[#F7F3EC] border border-[#062A43]/10 px-4 py-3"/>)}<label className="flex gap-2 items-center"><input type="checkbox" checked={form.has_3d} onChange={e=>setForm({...form,has_3d:e.target.checked})}/> دارای مدل سه‌بعدی</label>{error&&<p className="text-red-700 text-sm">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-[#062A43] text-[#D9AE62] py-3 font-bold">افزودن محصول</button></form><div className="space-y-3">{products.map(p=><div key={p.id} className="bg-[#FCFAF6] border border-[#B88A3A]/20 rounded-2xl p-4 flex items-center gap-4">{p.image?<img src={p.image} className="w-20 h-20 rounded-xl object-cover"/>:<div className="w-20 h-20 rounded-xl bg-[#F7F3EC]"/>}<div className="flex-1"><h3 className="font-black">{p.name}</h3><p className="text-[#B88A3A] font-bold">{p.price.toLocaleString("fa-IR")}</p><p className="text-xs text-[#6F6A62]">{p.tag||"بدون برچسب"}</p></div><button onClick={()=>remove(p.id)} className="p-3 rounded-full hover:bg-red-50 text-red-700"><Trash2 size={18}/></button></div>)}{!products.length&&!loading&&<div className="bg-[#FCFAF6] rounded-3xl p-10 text-center text-[#6F6A62]">محصولی ثبت نشده است.</div>}</div></div></>}
