"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ShoppingCart, Star } from "lucide-react";
import { motion } from "framer-motion";
import { createClient } from "@/utils/supabase/client";
import { useCart } from "@/context/CartContext";

type Product={id:string;name:string;price:number;original_price:number|null;image:string|null;tag:string|null;rating:number;color_options?:{name:string;value?:string}[]|null;discount_percent?:number};

export default function FeaturedProducts(){
 const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const {addLocalShopItem}=useCart();
 useEffect(()=>{let alive=true;(async()=>{const supabase=createClient();const {data}=await supabase.from("products").select("id,name,price,original_price,image,tag,rating,color_options,discount_percent").order("created_at",{ascending:false}).limit(8);if(alive)setProducts((data??[]) as Product[]);setLoading(false)})();return()=>{alive=false}},[]);
 if(!loading&&!products.length)return null;
 return <section className="w-full px-5 md:px-8 py-14 md:py-20 bg-[#F7F3EC] border-y border-[#062A43]/5"><div className="max-w-[1400px] mx-auto"><div className="flex items-end justify-between mb-9"><div><p className="text-[#B88A3A] font-bold mb-2">انتخاب ترنج</p><h2 className="text-2xl md:text-3xl font-black text-[#0B2942]">محصولات جدید</h2></div><Link href="/shop" className="hidden sm:flex items-center gap-2 text-[#B88A3A] font-bold">مشاهده همه <ArrowLeft size={17}/></Link></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">{products.map((p,i)=>{const disc=Number(p.discount_percent)||0;return <motion.article key={p.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.04}} className="bg-[#FCFAF6] rounded-2xl p-3 border border-[#062A43]/5 shadow-sm hover:shadow-lg transition-shadow"><Link href={`/shop?product=${p.id}`}><div className="relative aspect-[1.05] rounded-xl overflow-hidden bg-[#EDE6DC]">{p.image?<img src={p.image} alt={p.name} className="w-full h-full object-cover hover:scale-105 transition-transform duration-500"/>:<div className="w-full h-full"/>}{p.tag&&<span className="absolute top-3 right-3 bg-[#031C2E]/90 text-[#D9AE62] px-2.5 py-1 rounded-full text-xs font-bold">{p.tag}</span>}{disc>0&&<span className="absolute top-3 left-3 bg-[#B88A3A] text-white px-2.5 py-1 rounded-full text-xs font-bold">{disc}٪ تخفیف</span>}</div></Link><div className="px-2 pt-4 pb-2"><h3 className="font-bold text-[#0B2942] truncate">{p.name}</h3><div className="flex items-center gap-1 mt-1 text-xs text-[#6F6A62]"><Star size={13} className="fill-[#B88A3A] text-[#B88A3A]"/><span>{p.rating||5}</span>{p.color_options?.length?<><span>•</span><span>{p.color_options.length} رنگ</span></>:null}</div><div className="flex items-end justify-between mt-3"><div>{disc>0&&p.original_price?<div className="text-xs text-[#6F6A62] line-through">{Number(p.original_price).toLocaleString("fa-IR")} تومان</div>:null}<div className="font-black text-[#B88A3A]">{Number(p.price).toLocaleString("fa-IR")} تومان</div></div><button onClick={()=>addLocalShopItem(p.name,Number(p.price),p.image||"")} className="w-10 h-10 rounded-full bg-[#F7F3EC] text-[#062A43] hover:bg-[#062A43] hover:text-[#D9AE62] flex items-center justify-center transition-colors" aria-label="افزودن به سبد"><ShoppingCart size={18}/></button></div></div></motion.article>})}</div><Link href="/shop" className="sm:hidden mt-7 flex items-center justify-center gap-2 text-[#B88A3A] font-bold">مشاهده همه <ArrowLeft size={17}/></Link></div></section>;
}
