"use client";
import React,{createContext,useCallback,useContext,useEffect,useMemo,useState} from "react";
import type {CartItemWithProduct,Product} from "@/types/database";
import {addToCart,clearCart,getCartItems,removeFromCart,updateCartItemQuantity,claimGuestCart} from "@/lib/actions/cart";
import {type LocalCartItem,getLocalCart,addLocalShopItem,addLocalBuildItem,updateLocalItemQuantity,removeLocalItem as removeLocalItemUtil,clearLocalCart} from "@/lib/localCart";
import {createClient} from "@/utils/supabase/client";
type CartState={items:CartItemWithProduct[];localItems:LocalCartItem[];itemCount:number;subtotal:number;sessionId:string;isLoading:boolean;isDrawerOpen:boolean;openDrawer:()=>void;closeDrawer:()=>void;addItem:(product:Product)=>Promise<void>;addLocalShopItem:(name:string,price:number,image:string)=>void;addLocalBuildItem:(shape:string,fabric:string,fabricColor:string,legs:string,price:number)=>void;removeItem:(productId:string)=>Promise<void>;removeLocalCartItem:(id:string)=>void;updateQuantity:(productId:string,quantity:number)=>Promise<void>;updateLocalQuantity:(id:string,quantity:number)=>void;clearItems:()=>Promise<void>};
const CartContext=createContext<CartState|undefined>(undefined);
function getOrCreateSessionId(){if(typeof window==="undefined")return "";const s=localStorage.getItem("furnify_session_id");if(s)return s;const id=crypto.randomUUID();localStorage.setItem("furnify_session_id",id);return id;}
export function CartProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<CartItemWithProduct[]>([]),[localItems,setLocalItems]=useState<LocalCartItem[]>([]),[sessionId,setSessionId]=useState(""),[isLoading,setIsLoading]=useState(true),[isDrawerOpen,setIsDrawerOpen]=useState(false);const refresh=useCallback(async(s:string)=>{setIsLoading(true);setItems(await getCartItems(s));setIsLoading(false)},[]);
useEffect(()=>{setLocalItems(getLocalCart());const s=getOrCreateSessionId();setSessionId(s);(async()=>{await claimGuestCart(s);await refresh(s)})();const supabase=createClient();const{data:{subscription}}=supabase.auth.onAuthStateChange(async()=>{await claimGuestCart(s);await refresh(s)});return()=>subscription.unsubscribe()},[refresh]);
const ensure=useCallback(()=>sessionId||getOrCreateSessionId(),[sessionId]);const addItem=useCallback(async(p:Product)=>{const s=ensure();await addToCart(s,p.id);await refresh(s)},[ensure,refresh]);const removeItem=useCallback(async(id:string)=>{const s=ensure();await removeFromCart(s,id);await refresh(s)},[ensure,refresh]);const updateQuantity=useCallback(async(id:string,q:number)=>{const s=ensure();await updateCartItemQuantity(s,id,q);await refresh(s)},[ensure,refresh]);const clearItems=useCallback(async()=>{const s=ensure();await clearCart(s);clearLocalCart();setLocalItems([]);await refresh(s)},[ensure,refresh]);const value=useMemo(()=>({items,localItems,itemCount:items.reduce((n,i)=>n+i.quantity,0)+localItems.reduce((n,i)=>n+i.quantity,0),subtotal:items.reduce((n,i)=>n+Number(i.product.price)*i.quantity,0)+localItems.reduce((n,i)=>n+i.price*i.quantity,0),sessionId,isLoading,isDrawerOpen,openDrawer:()=>setIsDrawerOpen(true),closeDrawer:()=>setIsDrawerOpen(false),addItem,addLocalShopItem:(n:string,p:number,img:string)=>setLocalItems(addLocalShopItem(n,p,img)),addLocalBuildItem:(s:string,f:string,c:string,l:string,p:number)=>setLocalItems(addLocalBuildItem(s,f,c,l,p)),removeItem,removeLocalCartItem:(id:string)=>setLocalItems(removeLocalItemUtil(id)),updateQuantity,updateLocalQuantity:(id:string,q:number)=>setLocalItems(updateLocalItemQuantity(id,q)),clearItems}),[items,localItems,sessionId,isLoading,isDrawerOpen,addItem,removeItem,updateQuantity,clearItems]);return <CartContext.Provider value={value}>{children}</CartContext.Provider>}
export function useCart(){const c=useContext(CartContext);if(!c)throw new Error("useCart must be used within a CartProvider");return c}
